name: ssword_dotenv
version: 1.0.0

description: A fork of the dotenv package, mainly designed to support async I/O loading
repository: https://github.com/Ssword-dev/dart_ssword_dotenv
### TODO: Add a repository instead, i dont have any homepage
environment:
  sdk: '>=2.16.0 <4.0.0'

dependencies:
  args: ^2.3.0
  meta: ^1.7.0

dev_dependencies:
  tidy: ^3.1.0
  test: ^1.24.8
  collection: ^1.18.0
