name: dotenv
version: 3.0.0-nullsafety.0
description: Load environment variables from a `.env` file.
homepage: https://github.com/mockturtl/dotenv
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  args: ^2.1.0
  meta: ^1.3.0

dev_dependencies:
  tidy: ^2.12.0
  test: ^1.17.3
  collection: ^1.15.0
